### ISSUE TITLE
生成的RC显著图在配置OpenCV3.1时与论文结果有很大差别

### ISSUE THREAD

**Issue by Sucran** [MCG-NKU/CmCode#5]
程老师您好
我是去年十二月份下载的代码
代码生成的RC显著图和老师您2015TAPMI的论文结果有一点差别
差别在于，当我在做固定阈值实验的时候
MSRA1000的图集，阈值0，Precision是19%，recall 是100%，而您论文中的Precision是22%
我之前配置的OpenCV是2.4.9，配置没有问题，您代码中的配置问题我也参考了项目网站的Q&A
生成的RC显著图和论文中展示的有一定区别，但SalCut的结果数值和PR曲线也基本一致

抱着这样的疑问
我下载了最近更新的代码
我配置的是OpenCV3.1，配置没有问题，感谢您把项目中之前的问题解决了
但是我发现生成的RC显著图的结果与论文中展示的差别很大
就包括SalCut的分割结果也有很大不同
比如说，论文中图例6中展示的蒲公英图，现在更新的代码的分割结果就与论文的不一致，结果图多分割了一部分错误区域
而我之前十二月份下载的代码，分割的结果就和论文中的分割结果大致相同。

麻烦程老师关注一下这个问题，应该不是我的配置问题。

**Comment by gaochq** [comment]
我也出现了同样的问题，请问一下老师，应该是有什么地方造成的呢

**Comment by fuaiguo** [comment]
老师您好，我最近也遇到了和上面这位朋友一样的问题，RC的效果比较差，自己感觉着实不应该，HC效果很好，请问一下老师，您觉得这是什么原因造成的呢，谢谢老师解答

**Comment by JackeyDeng** [comment]
请问你们能找到RC算法中使用到的Region类吗，我怎么也找不到

**Comment by JackeyDeng** [comment]
> 老师您好，我最近也遇到了和上面这位朋友一样的问题，RC的效果比较差，自己感觉着实不应该，HC效果很好，请问一下老师，您觉得这是什么原因造成的呢，谢谢老师解答

请问你们能找到RC算法中使用到的Region类吗，我怎么也找不到

**Comment by JackeyDeng** [comment]
> 程老师您好
> 我是去年十二月份下载的代码
> 代码生成的RC显著图和老师您2015TAPMI的论文结果有一点差别
> 差别在于，当我在做固定阈值实验的时候
> MSRA1000的图集，阈值0，Precision是19%，recall 是100%，而您论文中的Precision是22%
> 我之前配置的OpenCV是2.4.9，配置没有问题，您代码中的配置问题我也参考了项目网站的Q&A
> 生成的RC显著图和论文中展示的有一定区别，但SalCut的结果数值和PR曲线也基本一致
> 
> 抱着这样的疑问
> 我下载了最近更新的代码
> 我配置的是OpenCV3.1，配置没有问题，感谢您把项目中之前的问题解决了
> 但是我发现生成的RC显著图的结果与论文中展示的差别很大
> 就包括SalCut的分割结果也有很大不同
> 比如说，论文中图例6中展示的蒲公英图，现在更新的代码的分割结果就与论文的不一致，结果图多分割了一部分错误区域
> 而我之前十二月份下载的代码，分割的结果就和论文中的分割结果大致相同。
> 
> 麻烦程老师关注一下这个问题，应该不是我的配置问题。

请问你们能找到RC算法中使用到的Region类吗，我怎么也找不到

**Comment by MingMingCheng** [comment]
Region 类在第50行 https://github.com/MCG-NKU/CmCode/blob/master/CmLib/Saliency/CmSaliencyRC.h

**Comment by MingMingCheng** [comment]
之前好像也碰到过有的OpenCV版本的某些次运行结果很奇怪。重新Ctrl+F5运行一次就好了。我也一直没深究过。
